# This is a basic workflow to help you get started with Actions

name: Combinate

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 1,11,23 * * *'
    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git pull
          git config --global user.email "AutoRobot@gmail.com"
          git config --global user.name "AutoRobot"
      
      - name: Install csh
        run: |
          sudo apt install csh
      
      - name: Main
        run: |
          pwd
         
          rm -rf ./TW.ch
          rm -rf ./TW

          # Build Source (cascade all source)
          cp ./Old/rslt ./rslt
          cat ./Source/rtmp ./Source/P2P ./rslt ./tw.src ./Source/bsexSmartTV  ./Source/P3P  > TW
          sed -i '/genre/d' ./TW


          # add catagory for TVBOX smart sorting 
          cat ./0_TW ./TW > TW0
          cat ./1_News ./TW > TW1
          cat ./2_Mix ./TW > TW2
          cat ./3_Movie ./TW > TW3
          cat ./4_Sport ./TW > TW4
          cat ./5_child ./TW > TW5

          ###########################################
          ## Create TVBOX Source
          
          # Cascade all 
          cat ./TW0 ./TW1 ./TW2 ./TW3 ./TW4 ./TW5 ./UBTV ./Source/P2P ./Source/bsexSmartTV ./Source/P3P ./UBTV18 > TW.ch
          rm -rf TW0
          rm -rf TW1
          rm -rf TW2
          rm -rf TW3
          rm -rf TW4
          rm -rf TW5
          rm -rf ./rslt



          ###########################################
          ## Create M3U 
          chmod +x ./run_class
          ./run_class
          
          rm -rf TW_allsource
          touch TW_allsource
          echo "新聞,#genre#" > a
          cat a parsing_TW.1_News >> TW_allsource
          echo "綜合,#genre#" > a
          cat a parsing_TW.2_Mix >> TW_allsource
          echo "電影,#genre#" > a
          cat a parsing_TW.3_Movie >> TW_allsource
          echo "體育,#genre#" > a
          cat a parsing_TW.4_Sport >> TW_allsource
          echo "親子,#genre#" > a
          cat a parsing_TW.5_child >> TW_allsource


          ###########################################
          ## Create ntPlayer Source
          grep -v 'test.m3u8' ./TW_allsource | grep -v "youtube.com" | grep -v "mitv:" | grep -v "P2p:" | grep -v "video:" | grep -v "p2p" | grep -v "p3p" > TW_txt

          

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet
              
      - name: Run Generate txt2m3u
        run: python ${{ github.workspace }}/txt2m3u.py
  
      - name: UpdateChannel Time 
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')" > UpdateTime
          
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Link updated"
          git push
