# This is a basic workflow to help you get started with Actions

name: Combinate

# Controls when the action will run. 
on:
  schedule:
    - cron: '5 1/4 * * *'
    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git pull
          git config --global user.email "GeniusWorker@gmail.com"
          git config --global user.name "GeniusWorker"
      
      - name: Install csh
        run: |
          sudo apt install csh
      
      - name: Get Source
        run: |

          #### Deliver UBSP ubvip1688
          chmod +x ./wolf.src
          ./wolf.src


      - name: Smart Parsing
        run: |
          rm -rf ./TW.ch
          rm -rf ./TW

          # Build Source 
          cp ./Old/rslt ./rslt
          cat ./Source/rtmp  ./Source/P2P ./rslt ./Source/SmartTV.txt ./Source/histar ./tw.src  ./Source/P3P ./Source/radio ./Source/BGM > TW
          sed -i '/genre/d' ./TW

          ##-----------------------------------------------##
          # Deliver : TW_allsorce (TVBox)
          # Deliver : TW_allsource2 (M3U)
          ##-----------------------------------------------##
          chmod +x ./run_class
          ./run_class

          # Re-target M3U
          mv ./TW_allsource2 ./m3u.src

          ####################################
          ## Copy parsing script
          ####################################
          cp ./Type/0_TW ./0_TW
          cp ./Type/1_News ./1_News
          cp ./Type/2_Mix ./2_Mix 
          cp ./Type/3_Movie ./3_Movie
          cp ./Type/4_Sport ./4_Sport
          cp ./Type/5_child ./5_child
          cp ./Type/6_Radio ./6_Radio
          cp ./Type/6_Know ./6_Know
          cp ./Type/7_BGM ./7_BGM
          cp ./Type/9_other ./9_other
          
          

          # add catagory for Smart parsing
          cat ./0_TW ./TW > TW0
          cat ./1_News ./TW > TW1
          cat ./2_Mix ./TW > TW2
          cat ./3_Movie ./TW > TW3
          cat ./4_Sport ./TW > TW4
          cat ./5_child ./TW > TW5

          # Cascade all for smart parsing
          cat ./TW0 ./TW1 ./TW2 ./TW3 ./TW4 ./TW5 ./UBTV ./Source/P2P  ./Source/P3P ./Source/radio ./Source/BGM ./UBTV18 > TW.ch
               
               
      - name: Remove redundancy
        run: |
          rm -rf TW0
          rm -rf TW1
          rm -rf TW2
          rm -rf TW3
          rm -rf TW4
          rm -rf TW5
          rm -rf ./rslt
          rm -rf ./live.txt
          rm -rf *.c

          rm -rf ./UBSP
          rm -rf ./Source/UBSP  
          rm -rf 0_TW 1_News 2_Mix 3_Movie 4_Sport 5_child
             

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet
              
      - name: Translate from txt to m3u
        run: |
          # Create Generate TXT to m3u Source
          
          cat ./m3u.src | grep -v 'test.m3u8' | grep -v "youtube.com" | grep -v "mitv:" | grep -v "P2p:" | grep -v "video:" | grep -v "p2p" | grep -v "p3p" > TW_txt      

          # Parsing script
          python ${{ github.workspace }}/txt2m3u.py
  
      - name: UpdateChannel Time 
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')" > UpdateTime
          
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Link updated"
          git push
